mode = "auto"

[git]

[git.config]
email = "skinner.david@gmail.com"
name = "comaldave"

[git.tags]
prefix = "v"
suffix = "-alpha"

[semver]
patch = ["fix", "bug"]
minor = ["feature","feat"]
major = ["release"]

[modes]

[modes.git-branch]
delimiters = "/"

[modes.git-commit]
delimiters = "[]"

